# Generated by Django 3.2 on 2023-01-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MRN', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ID_number', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('Nationality', models.CharField(choices=[('Saudi', 'Saudi'), ('non-Saudi', 'non-Saudi')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_name', models.CharField(choices=[('ER', 'ER'), ('pedia_ward', 'pedia_ward'), ('male_ward', 'male_ward'), ('female_ward', 'female_ward'), ('OB_ward', 'OB_ward'), ('L&D_ward', 'L&D_ward'), ('covid_ward', 'covid_ward'), ('OPD', 'OPD'), ('refferal', 'referral')], max_length=255)),
                ('status', models.CharField(choices=[('emergency/immediatly', 'emergency/immediatly'), ('urgent/24hrs', 'urgent/24hrs'), ('routine/ 48 hours', 'routine/ 48 hours')], max_length=255)),
                ('infectious_disease', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3)),
                ('way_of_transport', models.CharField(choices=[('walking', 'walking'), ('wheelchair', 'wheelchair'), ('trolley', 'trolley')], max_length=255)),
                ('is_new_request', models.BooleanField()),
                ('modalities', models.CharField(choices=[('CT', 'CT'), ('US', 'US'), ('X_ray', 'X_ray'), ('MRI', 'MRI'), ('Mammography', 'Mammography'), ('Angiogram.', 'Angiogram.'), ('Interventional radiological procedures', 'Interventional radiological procedures'), ('Fluoroscopy', 'Fluoroscopy'), ('Nuclear medicine imaging', 'Nuclear medicine imaging'), ('Molecular Imaging /Positron Emission Tomography /PET scanning', 'Molecular Imaging /Positron Emission Tomography /PET scanning'), ('Bedside /critical care radiography', 'Bedside /critical care radiography'), ('Portable radiological machines', 'Portable radiological machines')], max_length=255)),
                ('study_part', models.CharField(choices=[('Abdomen', 'Abdomen'), ('KUB', 'KUB'), ('OB less than 14 Weeks', 'OB less than 14 Weeks '), ('OB more than 14 Weeks', 'OB more than 14 Weeks '), ('Brain', 'Brain'), ('Neck', 'Neck'), ('Chest', 'Chest'), ('pelvis', 'pelvis'), ('pan-CT', 'pan-CT'), ('thyroid', 'thyroid'), ('breast', 'breast'), ('scrotal', 'scrotal'), ('cervical spine', 'cervical spine'), ('L/S spine', 'L/S spine'), ('D/L spine', 'D/L spine'), ('doppler-venous-lower', 'doppler-venous-lower'), ('doppler-arterial-lower', 'doppler-arterial-lower'), ('doppler-venous-upper', 'doppler-venous-upper'), ('doppler-arterial-upper', 'doppler-arterial-upper'), ('all spine', 'all spine'), ('Shoulder', 'Shoulder'), ('elbow', 'elbow'), ('wrist', 'wrist'), ('hand', 'hand'), ('hip', 'hip'), ('knee', 'knee'), ('ankle', 'ankle'), ('foot', 'foot'), ('other-study', 'other-study')], max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='radio.patient')),
            ],
        ),
    ]
