# Generated by Django 3.2 on 2023-01-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='is_new_request',
            field=models.CharField(choices=[('new', 'New Request'), ('followup', 'Follow Up')], default='new', max_length=255),
        ),
    ]
